# Generated by Django 4.2.20 on 2026-07-13 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('psychosphere', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='article',
            name='category',
        ),
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Redakcja PsychSphere', help_text='Imię i nazwisko autora wyświetlane przy artykule.', max_length=150),
        ),
        migrations.AddField(
            model_name='article',
            name='categories',
            field=models.ManyToManyField(related_name='articles', to='psychosphere.category', verbose_name='Kategorie'),
        ),
    ]
